name: automation to the page
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: github pages
        uses: actions/configure-pages@v3
      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with: 
          path: '.'
      - name: deploy page
        uses: actions/deploy-pages@v2
        
      
    
 
    
